# Generated by Django 5.0.7 on 2024-07-30 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Entrevista",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=255)),
                ("data", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Vaga",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome_vaga", models.CharField(max_length=255)),
                ("empresa", models.CharField(max_length=255)),
                ("detalhes", models.TextField()),
                ("salario", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="VagaC",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("empresa", models.CharField(max_length=255)),
                ("tempo", models.CharField(max_length=50)),
            ],
        ),
    ]
