# Generated by Django 5.0.7 on 2024-08-01 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_vaga_compativel'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaga',
            name='tipo',
            field=models.CharField(default='CLT', max_length=255),
        ),
    ]
